# Generated by Django 4.0.1 on 2022-02-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerName_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=50, unique=True)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('VehicleId', models.AutoField(default=2022, primary_key=True, serialize=False)),
                ('VehicleName', models.CharField(max_length=50)),
                ('VehicleType', models.CharField(max_length=50)),
                ('VehicleBrand', models.CharField(max_length=50)),
                ('VehicleColor', models.CharField(max_length=50)),
                ('VehicleModel', models.CharField(max_length=50)),
                ('VehiclePrice', models.IntegerField()),
                ('VehicleStatus', models.BooleanField(default=True)),
                ('VehicleInventory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RentBooking',
            fields=[
                ('BookingId', models.AutoField(default=786, primary_key=True, serialize=False)),
                ('VehicleType', models.CharField(max_length=50)),
                ('CustomerName', models.CharField(max_length=50)),
                ('RentDate', models.DateField()),
                ('ReturnDate', models.DateField(default=None)),
            ],
        ),
    ]
