# Generated by Django 4.0.1 on 2022-02-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclerent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CustomerName_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
