# Generated by Django 4.0.1 on 2022-02-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclerent', '0002_alter_customer_customername_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CustomerName',
            field=models.CharField(max_length=50),
        ),
    ]
