# Generated by Django 4.0.1 on 2022-02-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclerent', '0003_alter_customer_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbooking',
            name='BookingId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
