# Generated by Django 4.0.1 on 2022-02-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclerent', '0004_alter_rentbooking_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='VehicleId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
